name: Continuous VPS (GitHub-Hosted)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */5 * * *"  # every 5h30m (UTC approx)

jobs:
  vps-session:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2. Install prerequisites
    - name: Install prerequisites
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y curl unzip zip rsync wget docker.io docker-compose awscli

    # 3. Restore backup from S3
    - name: Download backup
      run: |
        mkdir -p ./backup
        aws s3 cp s3://YOUR_BUCKET_NAME/backup.zip ./backup/backup.zip || echo "No backup found"

    - name: Extract backup
      run: |
        if [ -f ./backup/backup.zip ]; then
          unzip -o ./backup/backup.zip -d /opt/vps-backup
        fi

    # 4. Install & connect Tailscale
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname gha-vps --accept-routes --accept-dns --ssh || echo "Tailscale may already be up"

    # 5. Start Playit agent
    - name: Start Playit
      run: |
        if [ ! -f ./playit-linux ]; then
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux
          chmod +x ./playit-linux
        fi
        mkdir -p ~/.playit
        cp -r /opt/vps-backup/data/playit/* ~/.playit/ || true
        nohup ./playit-linux &>/dev/null &

    # 6. Start Docker containers
    - name: Start Docker containers
      run: |
        if [ -f docker-compose.yml ]; then
          docker-compose up -d
        fi

    # 7. Show IPs
    - name: Show IPs
      run: |
        echo "Public IP via Playit:"
        cat ~/.playit/public-ip.txt || echo "Not found"
        echo "Tailscale IP:"
        tailscale ip -4

    # 8. Backup VPS to S3
    - name: Backup VPS
      run: |
        mkdir -p /opt/vps-backup/data/playit
        cp -r ~/.playit/* /opt/vps-backup/data/playit/ || true
        zip -r backup.zip /opt/vps-backup
        aws s3 cp backup.zip s3://YOUR_BUCKET_NAME/backup.zip
