name: Continuous VPS (Artifact-Based)

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "30 */5 * * *"  # ~5h30m auto-restart

jobs:
  vps-session:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Install prerequisites
    - name: Install prerequisites
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y curl unzip zip rsync wget docker.io docker-compose

    # 3. Install Tailscale
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    # 4. Restore backup from artifact
    - name: Download VPS backup
      uses: actions/download-artifact@v4
      with:
        name: vps-backup
        path: ./backup || echo "No previous backup found"

    - name: Extract Backup
      run: |
        if [ -f ./backup/backup.zip ]; then
          unzip -o ./backup/backup.zip -d /opt/vps-backup
        fi

    # 5. Connect Tailscale
    - name: Connect Tailscale
      run: |
        sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname gha-vps --accept-routes --accept-dns --ssh || echo "Tailscale may already be up"

    # 6. Start Playit agent
    - name: Start Playit
      run: |
        if [ ! -f ./playit-linux ]; then
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux
          chmod +x ./playit-linux
        fi
        mkdir -p ~/.playit
        cp -r /opt/vps-backup/data/playit/* ~/.playit/ || true
        nohup ./playit-linux &>/dev/null &

    # 7. Start Docker containers
    - name: Start Docker containers
      run: |
        if [ -f docker-compose.yml ]; then
          docker-compose up -d
        fi

    # 8. Show IPs
    - name: Show IPs
      run: |
        echo "Public IP via Playit:"
        cat ~/.playit/public-ip.txt || echo "Not found"
        echo "Tailscale IP:"
        tailscale ip -4
        docker ps

    # 9. Backup VPS for next run
    - name: Backup VPS
      run: |
        mkdir -p /opt/vps-backup/data/playit
        cp -r ~/.playit/* /opt/vps-backup/data/playit/ || true
        zip -r backup.zip /opt/vps-backup

    - name: Upload VPS backup artifact
      uses: actions/upload-artifact@v4
      with:
        name: vps-backup
        path: backup.zip
