name: Continuous Persistent VPS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"  # every 5 hours

permissions:
  contents: write  # allow backup commits

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5.5h runtime

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip sudo net-tools neofetch

      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore backup (Tailscale state + data)
        run: |
          if [ -f vps-backup.zip ]; then
            echo "Restoring backup..."
            sudo unzip -o vps-backup.zip -d /
          else
            echo "No backup found, starting fresh"
          fi

      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up \
            --authkey ${{ secrets.TAILSCALE_AUTHKEY }} \
            --hostname=biralo \
            --accept-dns=false \
            --reset || echo "Tailscale already up"

      - name: Create persistent user
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Show Tailscale IP
        run: |
          echo "✅ Connect using:"
          tailscale ip -4 | head -n 1 | xargs -I{} echo "ssh biralo@{}"

      - name: Keep VPS alive
        run: sleep 18000  # 5h

      - name: Backup VPS state
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/ || true
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r vps-backup.zip /opt/vps-backup

      - name: Commit and push backup
        run: |
          cp vps-backup.zip $GITHUB_WORKSPACE/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vps-backup.zip
          git commit -m "Auto backup $(date)" || echo "No changes"
          git push
