name: Persistent VPS

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: "0 */6 * * *"  # auto every 6 hours, change as needed

jobs:
  vps-session:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Checkout repo (if configs/scripts are in repo)
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Update packages
      - name: Update & Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl unzip zip net-tools sudo rsync docker.io containerd

      # 3️⃣ Restore Backup if exists
      - name: Restore Backup
        uses: actions/download-artifact@v3
        with:
          name: vps-backup
          path: ./backup.zip

      - name: Extract Backup
        run: |
          if [ -f ./backup.zip ]; then
            unzip -o ./backup.zip -d /
            echo "Backup restored"
          else
            echo "No backup found, starting fresh"
          fi

      # 4️⃣ Start Playit agent (auto-claim if first run)
      - name: Run Playit
        run: |
          mkdir -p ~/.playit
          if [ ! -f ~/.playit/playit.toml ]; then
            echo "First run: claim your Playit manually"
            echo "Go to https://playit.gg/claim and paste token/config"
            # You can also script auto token here if needed later
          fi
          # Start Playit
          nohup ./playit &  # make sure your Playit binary/script is in repo
          sleep 5
          echo "Playit Public IP:"
          grep "Tunnel:" ~/.playit/playit.log || echo "Check dashboard if not printed"

      # 5️⃣ Start Tailscale (auto-connect)
      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 5
          sudo tailscale up --authkey your-tailscale-key --accept-routes
          echo "Tailscale IP:"
          tailscale ip -4

      # 6️⃣ Start your other services
      - name: Start VPS Services
        run: |
          # Example: Docker containers
          docker compose -f /home/your-vps/docker-compose.yml up -d

      # 7️⃣ Backup data at end
      - name: Backup Data
        run: |
          zip -r backup.zip /home/your-vps-data ~/.playit /var/lib/tailscale /etc/your-service
          echo "Backup created"

      - name: Upload Backup
        uses: actions/upload-artifact@v3
        with:
          name: vps-backup
          path: backup.zip

      # ✅ Finished
      - name: Done
        run: echo "VPS is persistent! Playit + Tailscale running. Backup uploaded."
