name: Continuous Persistent VPS

on:
  workflow_dispatch:

jobs:
  persistent-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # 72 hours (max allowed)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Infinite persistent loop
        run: |
          while true; do
            echo "===== Starting VPS cycle ====="

            # Set hostname
            sudo hostnamectl set-hostname biralo

            # Restore backup
            if [ -f ./backup/backup.zip ]; then
              echo "Restoring backup..."
              sudo unzip -o ./backup/backup.zip -d /
            fi

            # Restore Tailscale
            if [ -f /opt/vps-backup/data/tailscaled.state ]; then
              sudo mkdir -p /var/lib/tailscale
              sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
              sudo chmod 600 /var/lib/tailscale/tailscaled.state
            fi

            # Start Tailscale
            sudo tailscaled &
            sleep 8
            sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

            # Create user
            if ! id -u biralo >/dev/null 2>&1; then
              sudo useradd -m -s /bin/bash biralo
              echo "biralo:biralo" | sudo chpasswd
              sudo usermod -aG sudo biralo
              echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
            fi

            # Start tmate session
            tmux new-session -d -s vps-session
            tmate -S /tmp/tmate.sock new-session -d
            tmate -S /tmp/tmate.sock wait tmate-ready
            echo "🔑 tmate SSH session:"
            tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'

            # Sleep for 5.5 hours
            sleep 19800

            # Backup VPS
            sudo mkdir -p /opt/vps-backup/data
            sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
            sudo chown -R $USER:$USER /opt/vps-backup
            zip -r backup.zip /opt/vps-backup

            # Upload backup artifact
            gh actions upload-artifact --name vps-backup --path backup.zip || echo "Backup upload failed"

            echo "===== Cycle complete, restarting ====="
          done
