name: Continuous Persistent VPS

on:
  schedule:
    - cron: '0 */6 * * *'   # fallback trigger every 6 hours
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 330   # 5h30m max runtime

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to biralo
        run: sudo hostnamectl set-hostname biralo

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y \
            tmate curl unzip sudo net-tools neofetch rsync zip docker.io

      - name: Enable systemd user services
        run: |
          sudo loginctl enable-linger $USER || true
          sudo systemctl daemon-reexec || true
          sudo systemctl daemon-reload || true

      - name: Restore full VPS backup
        run: |
          if [ -f ./backup/backup.zip ]; then
            echo "Restoring VPS from backup..."
            sudo unzip -o ./backup/backup.zip -d /

            sudo systemctl daemon-reexec || true
            sudo systemctl daemon-reload || true

            # Restart all enabled services
            for svc in $(systemctl list-unit-files --state=enabled --no-pager --no-legend | awk '{print $1}'); do
              sudo systemctl restart "$svc" || true
            done

            # Restore Docker containers
            if command -v docker >/dev/null 2>&1; then
              sudo systemctl restart docker || true
              sleep 5
              if [ -f /opt/vps-backup/data/running-containers.list ]; then
                echo "Restoring Docker containers..."
                for c in $(cat /opt/vps-backup/data/running-containers.list); do
                  sudo docker start "$c" || true
                done
              fi
            fi
          else
            echo "⚠️ No backup found, starting fresh"
          fi

      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi

      - name: Start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo with sudo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show Tailscale IP
        run: |
          echo "🔗 Tailscale IP:"
          tailscale ip -4 || echo "Tailscale IP not found"

      - name: Sleep until restart
        run: sleep 19800   # 5h30m

      - name: Create VPS backup
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/ || true

          # Save running containers
          sudo docker ps -q > /opt/vps-backup/data/running-containers.list || true

          echo "Backing up filesystem..."
          sudo rsync -a \
            --exclude={"/opt/vps-backup","/proc/*","/sys/*","/dev/*","/tmp/*","/run/*"} \
            / /opt/vps-backup/full

          echo "Creating zip..."
          cd /
          sudo zip -qry /backup.zip opt/vps-backup || true
          ls -lh /backup.zip || echo "⚠️ backup.zip missing"

      - name: Upload VPS backup artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: /backup.zip
          retention-days: 90

      - name: Auto-dispatch next run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Triggering next run..."
          gh workflow run "Continuous Persistent VPS" || true
