name: Continuous Persistent VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo (optional, for workflow scripts)
    - name: Checkout repo
      uses: actions/checkout@v4

    # 2. Update system & install prerequisites
    - name: Install prerequisites
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y curl unzip zip rsync sudo net-tools software-properties-common apt-transport-https ca-certificates gnupg lsb-release

    # 3. Install Docker (stable)
    - name: Install Docker
      run: |
        sudo apt-get remove -y containerd containerd.io || true
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
        sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
        sudo systemctl enable docker
        sudo systemctl start docker

    # 4. Install Tailscale
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey ${TAILSCALE_AUTHKEY:-""} || echo "Use manual auth if key not set"

    # 5. Restore VPS backup (auto)
    - name: Restore Backup
      uses: actions/download-artifact@v4
      with:
        name: vps-backup
        path: ./backup.zip

    - name: Extract Backup
      run: |
        if [ -f ./backup.zip ]; then
          unzip -o ./backup.zip -d /opt/vps-backup
        fi

    # 6. Start Playit (auto-start with claimed port)
    - name: Start Playit agent
      run: |
        # Download Playit agent if missing
        if [ ! -f ./playit-linux ]; then
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux
          chmod +x ./playit-linux
        fi

        # Restore Playit config if exists
        if [ -d /opt/vps-backup/data/playit ]; then
          cp -r /opt/vps-backup/data/playit ~/.playit
        fi

        # Start Playit in background
        nohup ./playit-linux &>/dev/null &

    # 7. Start Docker containers
    - name: Start Docker containers
      run: |
        if [ -f docker-compose.yml ]; then
          docker compose up -d
        fi

    # 8. Show public IPs
    - name: Show IPs
      run: |
        echo "Public IPv4 via Playit:"
        cat ~/.playit/public-ip.txt || echo "Playit IP not found"
        echo "Tailscale IP:"
        tailscale ip -4

    # 9. Auto-backup VPS state
    - name: Backup VPS
      run: |
        mkdir -p /opt/vps-backup/data/playit
        cp -r ~/.playit/* /opt/vps-backup/data/playit/ || true
        zip -r backup.zip /opt/vps-backup
    - name: Upload Backup
      uses: actions/upload-artifact@v4
      with:
        name: vps-backup
        path: backup.zip
