name: Continuous Persistent VPS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"  # every 5 hours

permissions:
  contents: write  # allow pushing backups
  actions: write   # allow triggering workflows

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5.5h max runtime

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Restore backup
        run: |
          if [ -f vps-backup.zip ]; then
            echo "Restoring backup..."
            sudo unzip -o vps-backup.zip -d /
          else
            echo "No backup found, starting fresh"
          fi

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=biralo || echo "Tailscale already up"

      - name: Create user biralo
        run: |
          if ! id -u biralo >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash biralo
            echo "biralo:biralo" | sudo chpasswd
            sudo usermod -aG sudo biralo
            echo "biralo ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/biralo
          fi

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run VPS workload
        run: sleep 18000  # keep alive for 5h

      - name: Backup VPS data
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r vps-backup.zip /opt/vps-backup

      - name: Commit and push backup
        run: |
          cp vps-backup.zip $GITHUB_WORKSPACE/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vps-backup.zip
          git commit -m "Auto backup $(date)" || echo "No changes"
          git push

  handover:
    runs-on: ubuntu-latest
    needs: vps
    if: always()
    steps:
      - name: Trigger next run
        run: |
          echo "Triggering next run..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
            -d '{"ref":"main"}'
